### ISSUE TITLE
Display properties #415

### ISSUE THREAD

**Issue by Ofili-Louis** [9AppSoft-Public-Repos/Restaurant1#3]
This requires sending a message to the display side and getting a value back. We don't currently have a convenient way to do that (possible, yes, convenient, no.)

Display properties will need to be able to override styles in many cases -- starting with width and height where, as stated above, the display property is a different thing than the Shoes style with the same name.

**Comment by egojoseph** [comment]
The display configuration fix has been updated correctly.

**Comment by egojoseph** [comment]
fixed
